= Mobile App Self-Defence

|===
|Do's |Dont's

|*Detect compromised environments (rooted/jaibreak) at runtime and react accordingly* _(Ensure the environment is not tampered with)_
|*Obfuscation is not protection, assume everything in the code is public.* _(Application code *can* be deobfuscated)_

|*Integrity check of the binary* _(Ensure the app itself is not tampered with)_
|

|*Verify and check the integrity of dynamic resources* _(Ensure those resources are not tampered with)_
|

|*Disable debugging in the application settings* _(Make sure the app is not debuggable)_
|

|*Check if the device is in developer mode if supported by platform* _(Prevent app debugging)_
|

|*Check if debugger is attached and/or if the process is being traced* _(Prevent app debugging)_
|

|*Check lockscreen/passcode is enabled on the device* _(Make sure device is secure)_
|

|*Consider blocking access if devices are out of date* _(Ensure device has no known vulnerabilities)_
|

|*Verify that the app implements two or more functionally independent methods of root detection.* _(Use a dual verification approach)_.
|

|*Verify that the app implements multiple functionally independent debugging defences.* _(Prevent a debugger from being attached that can view app data)._
|

|*Verify that the app detects, and response to, being run in an emulator using any method.* _(An emulator can be tampered with more easily than a hardware device)_.
|

|*Verify that the app detects, and responds to, modifications of process memory, including relocation table patches and injected code.* _(Ensure that the operating environment of the App is safe before running it.)_
|

|*Verify all executable files and libraries belonging to the app are either encrypted on the file level and/or important code and data segments inside the executables are encrypted or packed.* _(Sensitive or secret code/resources should be protected.)_
|

|*Verify that the app implements a 'device binding' functionality when a mobile device is treated as being trusted. Verify that the device fingerprint is derived from multiple device properties.* _(Improve device identity/integrity)._
|

|*Verify that if the architecture requires sensitive computations be performed on the client-side, these computations are isolated from the operating system by using a hardware-based SE or TEE.* _(Sensitive operations should be carried out away from the main processor in a Trusted Execution Environment)._
|

|*Perform user interaction anomaly detection.* _(Allows the identification of abnormal app usage by a user that may be malicious)._
|

|*Consider only starting the app if it is running on the latest version or block requests from old versions of the app.* _(Older versions maybe have logic or security issues)._
|

|*Out-of-appstore security updates should be shipped using an encrypted connection.* _(Ensure that the security patch has not been tampered with in transit)._
|

|*Ensure that the installation package and its updates shall be digitally signed such that its platform can cryptographically verify them prior to installation.* _(Verify integrity before applying the update)._
|
|===

== Implementation
=== Overview
A number of checks were implemented to assess the security of the underlying device running both the Android and iOS template applications.

=== Android
The main code logic is found under https://github.com/feedhenry/mobile-security-android-template/tree/master/app/src/main/java/com/feedhenry/securenativeandroidtemplate/features/device[here].

The following code snippets below describe the main device trust detection logic in the mobile app.

==== Detecting Root Access
Device Root Access detection has been added using the https://github.com/scottyab/rootbeer[Rootbeer] library. This library uses a number of different checks to check if root access is present on the device.

.Code
[source,java,linenums,indent=0]
....
include::https://raw.githubusercontent.com/feedhenry/mobile-security-android-template/master/app/src/main/java/com/feedhenry/securenativeandroidtemplate/features/device/DeviceFragment.java[tags=detectRoot]
....

==== Detecting if Lock Screen Set
Detecting if the Android device has a lock screen set (with pin, fingerprint, pattern etc) can be checked using the https://developer.android.com/reference/android/app/KeyguardManager.html[KeyguardManager] class in Android M or higher.

.Code
[source,java,linenums,indent=0]
....
include::https://raw.githubusercontent.com/feedhenry/mobile-security-android-template/master/app/src/main/java/com/feedhenry/securenativeandroidtemplate/features/device/DeviceFragment.java[tags=detectDeviceLock]
....

==== Detecting if Debugger is Attached
Detecting if an Android debugger is attached to the application can be checked using the https://developer.android.com/reference/android/os/Debug.html[Debug] class.

.Code
[source,java,linenums,indent=0]
....
include::https://raw.githubusercontent.com/feedhenry/mobile-security-android-template/master/app/src/main/java/com/feedhenry/securenativeandroidtemplate/features/device/DeviceFragment.java[tags=debuggerDetected]
....

==== Detecting Emulator Access
Detecting if the Application is being run on an emulator can be performed by checking a number of sources for evidence of emulator access.

.Code
[source,java,linenums,indent=0]
....
include::https://raw.githubusercontent.com/feedhenry/mobile-security-android-template/master/app/src/main/java/com/feedhenry/securenativeandroidtemplate/features/device/DeviceFragment.java[tags=isEmulator]
....

==== Detecting Hooking Framework Apps
There are some simple checks added to the application to check if the http://repo.xposed.info/module/de.robv.android.xposed.installer[Xposed Framework] or http://www.cydiasubstrate.com[Cydia Substrate] are installed on the device, which can be used to attack and tamper with logic in an Android applications.

.Code
[source,java,linenums,indent=0]
....
include::https://raw.githubusercontent.com/feedhenry/mobile-security-android-template/master/app/src/main/java/com/feedhenry/securenativeandroidtemplate/features/device/DeviceFragment.java[tags=detectHookingFramework]
....

==== Detecting App Data Backup Enabled
The application can check if the `allowBackup` flag in the applications `AndroidManifest.xml` file is set to true. If this flag is set to true, it is possible for an attacker to recover application data from the device without requiring root access.

.Code
[source,java,linenums,indent=0]
....
include::https://raw.githubusercontent.com/feedhenry/mobile-security-android-template/master/app/src/main/java/com/feedhenry/securenativeandroidtemplate/features/device/DeviceFragment.java[tags=detectBackupEnabled]
....

==== Detecting Out of Date OS Version
The devices OS version can be checked using the https://developer.android.com/reference/android/os/Build.html[Build] class to see if the device is not running the latest of Android.

.Code
[source,java,linenums,indent=0]
....
include::https://raw.githubusercontent.com/feedhenry/mobile-security-android-template/master/app/src/main/java/com/feedhenry/securenativeandroidtemplate/features/device/DeviceFragment.java[tags=detectLatestOS]
....

==== Detecting Developer Mode Enabled
The Developer Mode status can be checked using the https://developer.android.com/reference/android/provider/Settings.html[Settings] class in Android.

.Code
[source,java,linenums,indent=0]
....
include::https://raw.githubusercontent.com/feedhenry/mobile-security-android-template/master/app/src/main/java/com/feedhenry/securenativeandroidtemplate/features/device/DeviceFragment.java[tags=detectDeveloperOptions]
....

=== Native iOS

The following code snippets below describe the main device trust detection logic in the iOS template app.

==== Detecting Device Lock
Detecting if the Device has a lock screen set.

.Code
[source,swift,linenums,indent=0]
....
include::https://raw.githubusercontent.com/feedhenry/mobile-security-ios-template/master/secure-ios-app/services/DevicetrustService.swift[tags=detectDeviceLock]
....

==== Detecting Jailbreak
Detecting if the Device is Jailbroken using the https://github.com/thii/DTTJailbreakDetection[DTTJailbreakDetection] library.

.Code
[source,swift,linenums,indent=0]
....
include::https://raw.githubusercontent.com/feedhenry/mobile-security-ios-template/master/secure-ios-app/services/DevicetrustService.swift[tags=detectJailbreak]
....

==== Detecting Debug Mode
Detecting if the device is running in Debug mode.

.Code
[source,swift,linenums,indent=0]
....
include::https://raw.githubusercontent.com/feedhenry/mobile-security-ios-template/master/secure-ios-app/services/DevicetrustService.swift[tags=detectDebugabble]
....

==== Detecting Emulator Access
Detecting if the underlying device running the mobile application is an Emulator.

.Code
[source,swift,linenums,indent=0]
....
include::https://raw.githubusercontent.com/feedhenry/mobile-security-ios-template/master/secure-ios-app/services/DevicetrustService.swift[tags=detectEmulator]
....

==== Detecting Outdated OS Versions
Detecting if the underlying device running the mobile application is running an old version of iOS.

.Code
[source,swift,linenums,indent=0]
....
include::https://raw.githubusercontent.com/feedhenry/mobile-security-ios-template/master/secure-ios-app/services/DevicetrustService.swift[tags=detectLatestOS]
....
